// Script này return raw JS string được inject vào <script> tag của storefront.
// Vite bundle file này nên KHÔNG được dùng bất kỳ runtime expression nào —
// toàn bộ JS output phải là string literal cứng.
export function storefrontPurchaseToastScript(): string {
  return ';(function purchaseToastInit(){'
    + 'var U=["anhtuan","minhkhoi","thuynguyen","hoanganh","quocbao","ngoclinh","thanhhoa","ducmanh","kimchi","bichvan","trungkien","mylinh","songtung","haidang","phuongnam","lanhuong","vietanh","thanhlong","minhchau","quynhmai","tuananh","huongly","baominh","thanhvan","phucdat","tuyetmai","khanhlinh","namphong","binhan","haianh"];'
    + 'var t=null;'
    + 'function gp(){try{return(typeof allProducts!=="undefined"&&Array.isArray(allProducts)&&allProducts.length>0)?allProducts:null;}catch(e){return null;}}'
    + 'function show(){'
    +   'var products=gp();'
    +   'if(!products){t=setTimeout(show,2000);return;}'
    +   'var product=products[Math.floor(Math.random()*products.length)];'
    +   'var u=U[Math.floor(Math.random()*U.length)];'
    +   'var box=document.getElementById("purchaseToastContainer");'
    +   'if(!box)return;'
    +   'var name=(product.name||"sản phẩm").replace(/[<>]/g,"");'
    +   'var thumb=product.thumbnail||"";'
    +   'var wrap=document.createElement("div");'
    +   'wrap.style.cssText="display:flex;align-items:center;gap:10px;background:#fff;border-radius:14px;border-left:4px solid #e84393;padding:12px 14px;box-shadow:0 8px 28px rgba(15,23,42,0.13);min-width:240px;max-width:310px;pointer-events:auto;opacity:0;transform:translateY(16px);transition:opacity 0.4s ease,transform 0.4s ease;";'
    +   'var left=document.createElement("div");'
    +   'if(thumb){'
    +     'var img=document.createElement("img");'
    +     'img.src=thumb;img.alt="";'
    +     'img.style.cssText="width:40px;height:40px;object-fit:cover;border-radius:8px;flex-shrink:0;border:1.5px solid rgba(232,67,147,0.22);";'
    +     'left.appendChild(img);'
    +   '}else{'
    +     'left.style.cssText="width:40px;height:40px;border-radius:8px;background:linear-gradient(135deg,#e84393,#c0392b);display:flex;align-items:center;justify-content:center;flex-shrink:0;font-size:20px;";'
    +     'left.textContent="\\uD83D\\uDED2";'
    +   '}'
    +   'var right=document.createElement("div");'
    +   'right.style.cssText="min-width:0;";'
    +   'var top=document.createElement("div");'
    +   'top.style.cssText="font-size:11px;color:#9ca3af;font-weight:500;margin-bottom:3px;";'
    +   'top.textContent="\\uD83D\\uDD34 Vừa mua xong";'
    +   'var msg=document.createElement("div");'
    +   'msg.style.cssText="font-size:13px;line-height:1.4;color:#374151;";'
    +   'msg.innerHTML="Khách <strong style=\\\"color:#e84393;\\\">"+u+"</strong> vừa mua 1 <strong style=\\\"color:#111827;\\\">"+name+"</strong>";'
    +   'right.appendChild(top);right.appendChild(msg);'
    +   'wrap.appendChild(left);wrap.appendChild(right);'
    +   'box.appendChild(wrap);'
    +   'requestAnimationFrame(function(){requestAnimationFrame(function(){wrap.style.opacity="1";wrap.style.transform="translateY(0)";});});'
    +   't=setTimeout(function(){'
    +     'wrap.style.opacity="0";wrap.style.transform="translateY(-8px)";'
    +     'setTimeout(function(){if(wrap.parentNode)wrap.parentNode.removeChild(wrap);t=setTimeout(show,1000);},400);'
    +   '},5000);'
    + '}'
    + 't=setTimeout(show,5000);'
    + '})();'
}
